### ISSUE TITLE
Graphs are not showing up

### ISSUE THREAD

**Issue by daveajstearns** [learn-co-curriculum/dsc-derivatives-intro-lab#1]
Graphs seem to have not been showing up in my browser the past few lessons

**Comment by jessepisel** [comment]
Thanks for opening this issue @daveajstearns :wave:. I have not been able to replicate the issue above on my local machine. The latest commit https://github.com/learn-co-curriculum/dsc-derivatives-intro-lab/commit/09985392694d3fdf9038691823a6abc9e82c7571 has the graphs plotting in the notebook. 

One option for forcing `matplotlib` to plot in a notebook is to use the magic function `%matplotlib inline`. There is more information on how it works [here](https://stackoverflow.com/questions/43027980/purpose-of-matplotlib-inline).

However, the most recent versions of `ipython` which runs `jupyter` [does not need that magic function](https://github.com/ipython/ipython/issues/12190#issuecomment-598991796) for plotting any more. Try running `conda update ipython` in your terminal to update `ipython` to the latest version which should resolve this issue. 

I am closing this issue at this time. If you still cannot get the graphs to show up after updating `ipython` please reopen this issue.
